services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mopotsyo-app
    container_name: mopotsyo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - mopotsyo-network

  web:
    image: nginx:alpine
    container_name: mopotsyo-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - mopotsyo-network

  db:
    image: mysql:8.0
    container_name: mopotsyo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mopotsyo-network

  mail:
    image: axllent/mailpit
    container_name: mopotsyo-mail
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - mopotsyo-network

networks:
  mopotsyo-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
